# -*- coding: utf-8 -*-

import numpy as np

print("## concatenate two arrays:")
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
print(np.concatenate([arr1, arr2], axis=0))
print(np.concatenate([arr1, arr2], axis=1))
print()
print("## stack arrays:")
print(np.vstack((arr1, arr2)))
print(np.hstack((arr1, arr2)))

print("## split an array:")
arr = np.random.randn(5, 5)
print(arr)
print("### split along dim 0:")
first, second, third = np.split(arr, [1, 3], axis=0)
print("first:")
print(first)
print("second:")
print(second)
print("third:")
print(third)
print("### split along dim 1:")
first, second, third = np.split(arr, [1, 3], axis=1)
print("first:")
print(first)
print("second:")
print(second)
print("third:")
print(third)
print()

print("## pile arrays:")
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
print("### pile arrays along dim 0:")
print(np.r_[arr1, arr2])
print("### pile arrays along dim 1:")
print(np.c_[np.r_[arr1, arr2], arr])

print("### pile slice into an array:")
print(np.c_[1:6, -10:-5])
